### ISSUE TITLE
file_id is missing

### ISSUE THREAD

**Issue by amabdallah** [hydroshare/hs_restclient#106]
Did you guys drop the [id] from files? 

This piece of code used to work fine before but now I found out there is no more [id] returned which then I can't upload the spatial extent 
    spatial=hs.resource(resource_id).files.metadata(file_id, params)

![Capture](https://user-images.githubusercontent.com/3268971/56085885-af946c80-5e08-11e9-8deb-e16aaf838e84.PNG)

**Comment by sblack-usu** [comment]
@amabdallah - You can use the path with the filename now, so in your case you could just pass in `Bear_Weber.sqlite` in place of the file_id

**Comment by amabdallah** [comment]
Thanks @sblack-usu 
It makes more sense or at least much easier to use the file name. I'll update my code and it should work fine.
Adel
