### ISSUE TITLE
Missing license file and specification

### ISSUE THREAD

**Issue by ocefpaf** [hydroshare/hs_restclient#107]
There is no license file and `BSD` has, at least, 3 different versions. It would be nice to know which one this package is licensed under so we can package it downstream.

**Comment by sblack-usu** [comment]
@dtarb @martinseul - Would you like to consider a license for hs_restclient?

**Comment by horsburgh** [comment]
Is there a reason why it should be different than the one used for the main HydroShare codebase? BSD 3-Clause.

**Comment by sblack-usu** [comment]
I don't see why not, just raising the issue to those who need to give input for the license.

**Comment by dtarb** [comment]
We set policy long enough ago that it has been forgotten that all HydroShare code should use the BSD-3-Clause license by default (and only deviate if there was proper reason).

**Comment by sblack-usu** [comment]
I went ahead and added a copy of the LICENSE.txt file from hydroshare to hs_restclient.

https://github.com/hydroshare/hs_restclient/blob/develop/LICENSE.txt
