### ISSUE TITLE
Received status 504: Gateway Time-out

### ISSUE THREAD

**Issue by amabdallah** [hydroshare/hs_restclient#124]
Hi @sblack-usu and @Castronova 

Any clue why I'm getting this error message? It's the very basic code to access my account 

username = 'username'

password = 'password'

auth = HydroShareAuthBasic(username=username, password=password)

hs = HydroShare(auth=auth)

for resource in hs.resources():
    print 'Connected to HydroShare'

> Traceback (most recent call last):
  File "C:/Users/Rosenberg/Documents/GitHub/WaMDaM_Wizard_1.05-2.7/src/controller/HydroShare/trash.py", line 13, in <module>
    for resource in hs.resources():
  File "C:\Python27\lib\site-packages\hs_restclient\generators.py", line 12, in resultsListGenerator
    raise HydroShareHTTPException(r)
hs_restclient.exceptions.HydroShareHTTPException: Received status 504 <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.11.13</center>
</body>
</html>
 when accessing https://www.hydroshare.org/hsapi/resource/ with method GET.

![image](https://user-images.githubusercontent.com/3268971/83953485-0d022e80-a7fe-11ea-8a4e-7bf7c6d5f8f2.png)

**Comment by sblack-usu** [comment]
that endpoint performs terribly when no filters are provided.  Try listing just published resource 
```
for resource in hs.resources(published=True):
    print(resource)
```
This is an issue we're working through, but filtering your resources will help you for now.

**Comment by amabdallah** [comment]
@sblack-usu thank you, it worked. 
What I'm trying to do as a first step here is just to connect to hs and validate user credentials. Is there a better way to do that? Ideally there should be a parameter coming back with valid or invalid connection value and I can just look into it without needing to do this hs.resources().

I added a break, for now, to stop the for loop after getting the first resource which implicitly means the credentials are valid  

`			for resource in hs.resources(published=True):
				print("success")
				self.btn_login.Enabled = False
				break`

**Comment by Castronova** [comment]
@amabdallah Take a look at how I validate user credentials in the `hstools` application: https://github.com/Castronova/hstools/blob/master/hstools/auth.py.  After I instantiate a connection with HydroShare, I make a simple `getUserInfo` request. This request raises an exception if the login failed

```
try:
    a = hs_restclient.HydroShareAuthBasic(username=creds['usr'], password=creds['pwd'])
    hs = hs_restclient.HydroShare(auth=a)
    hs.getUserInfo()
    return hs
except Exception as e:
    raise Exception(e)
```

**Comment by Castronova** [comment]
> that endpoint performs terribly when no filters are provided. Try listing just published resource
> 
> ```
> for resource in hs.resources(published=True):
>     print(resource)
> ```
> 
> This is an issue we're working through, but filtering your resources will help you for now.

@sblack-usu Not sure if you saw this in the HydroShare project, but we might need to take a close look at the resource filtering logic. It appears that the `published` filter is returning non-published resources: https://github.com/hydroshare/hydroshare/issues/3868

**Comment by sblack-usu** [comment]
https://github.com/hydroshare/hydroshare/pull/3880 addresses the performance of the resources endpoint.  It will be included in the next release in the coming weeks.
