### ISSUE TITLE
Provide a method for getting a list of file names in the resource bag

### ISSUE THREAD

**Issue by danames** [hydroshare/hs_restclient#13]
It would be very useful to get a list of the file names so that you know what files are available to use with the getResourceFile() function.

**Comment by horsburgh** [comment]
@danames - this information should be in the resource map.  I believe we had a function designed for retrieving the resource map document, but I'm not sure whether it has been implemented yet.

**Comment by dtarb** [comment]
The link http://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b/data/resourcemap.xml  will return the resource map document.

**Comment by danames** [comment]
This should be easy to add to the Python API since there is an endpoint to
retrieve the file contents.

**Comment by selimnairb** [comment]
This relates to https://github.com/hydroshare/hydroshare/issues/601
