### ISSUE TITLE
createResource: what is the token in HydroShareAuthOAuth2 ?

### ISSUE THREAD

**Issue by yanliu-chn** [hydroshare/hs_restclient#20]
Is it the access token or the authorize token? I tried with a valid access token, and got:

`>>> auth = HydroShareAuthOAuth2(client_id, client_secret, token='___myaccesstoken___')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/smallblockFS/home/gisolve/cybergis/taudem/pyenv/lib/python2.6/site-packages/hs_restclient/__init__.py", line 911, in __init__
    self.token['expires_at'] = int(time.time()) + int(self.token['expires_in']) - EXPIRES_AT_ROUNDDOWN_SEC
TypeError: string indices must be integers, not str`

Also, is there a way to directly use a valid access token in the python client to get a session?

Finally, can someone show me a CURL way to createResource? I tried:
`curl -i -XPOST -F "title=pitremove_logan"  -F "resource_type=RasterResource" -F file=@`pwd`/afel.tif -L --header "Authorization: Bearer ___myaccesstoken___" http://www.hydroshare.org/hsapi/resource/
{"resource_type":"GenericResource","resource_id":"ba8d26d2163e4721b53c94a72fab2623"}`

The resource is created, but none of the fields I specified was taken by HS, including the title.

**Comment by selimnairb** [comment]
@yanliu-chn Please close this issue if it has been resolved elsewhere.  Thanks.
