### ISSUE TITLE
Add functionality to support new HydroShare REST endpoints

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hs_restclient#54]
The following new endpoints need to be supported:
-  [x] Unzip file
-  [x]  Zip folder
-  [x] Move file/folder
-  [x] Add key/value resource level metadata
-  [x] Set other resource flags 
-  [x] Create resource version 
-  [x] Create resource copy

**Comment by aphelionz** [comment]
@pkdash Thanks for making this ticket and enumerating what needed work. Would you prefer if I did this so you could focus on other work? I'm happy and available to support you either way.

**Comment by pkdash** [comment]
@aphelionz If you can work on this that would be great. Thanks.

**Comment by aphelionz** [comment]
@pkdash I'd like to close this issue and break it up into two smaller tickets:
- Upload endpoint
- @horsburgh's discovery endpoints

Any objections?

**Comment by horsburgh** [comment]
@aphelionz - fine by me.

**Comment by pkdash** [comment]
@aphelionz sounds good to me.

**Comment by aphelionz** [comment]
@pkdash Please review. I will create secondary tickets now
