### ISSUE TITLE
Documentation needs to be clarified for `start`, `count`, `from_date`, and `to_date` arguments

### ISSUE THREAD

**Issue by sdc50** [hydroshare/hs_restclient#77]
The documentation does not make it clear what the following arguments do:

`start`
`count`
`from_date`
`to_date`

After playing around with them my assumption is that:

- `start` allows you to specify the index of the resource to start querying from
- `count` allows you to specify how many resources to include in the query results
- `from_date` allows you to specify the earliest creation date to query for
- `to_date` allows you to specify the latest creation date to query for

Are these assumptions correct? Clarifying this in the documentation would be helpful.

**Comment by aphelionz** [comment]
Thanks! Just added these to the docs. New release is going out today. I'll let you know when.
