### ISSUE TITLE
Failed to update some metadata terms

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hs_restclient#97]
No error received. But they didnt get updated. 
       
        # not working!!!!
        # hs rights/license
        right_dict = {'statement': 'This is the rights statement for this resource',
                            'url': 'http://rights.ord/001', }
        science_metadata_json =hs.updateScienceMetadata( resource_id, metadata={'rights': [right_dict]})      

        # not working !!!!
        # hs funding
        agent_dict = {"agency_name": "National Science Foundation",
                      "award_title": "CZO",
                      "award_number": "NSF_123456789",
                      "agency_url": "http://www.nsf.gov",}
        science_metadata_json =hs.updateScienceMetadata( resource_id,  metadata={'funding_agencies': [agent_dict]})

**Comment by sblack-usu** [comment]
The rest_api parses this incorrectly and places your dict inside the statement key...
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L3528
It's an easy enough fix to put it in the correct key.

**Comment by sblack-usu** [comment]
Moving this work to hydroshare.  https://github.com/hydroshare/hydroshare/issues/3088
